apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tkeel
  namespace: {{ .Release.Namespace | quote }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host.admin }}
      http:
        paths:
          - backend:
              service:
                name: keel
                port:
                  number: 31234
            path: /apis/
            pathType: Prefix
          - backend:
              service:
                name: keel
                port:
                  number: 31234
            path: /static/
            pathType: Prefix
          - backend:
              service:
                name: console-portal-admin
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: core-broker
                port:
                  number: 31234
            path: /v1/ws
            pathType: Prefix
    - host: {{ .Values.ingress.host.tenant }}
      http:
        paths:
          - backend:
              service:
                name: keel
                port:
                  number: 31234
            path: /apis/
            pathType: Prefix
          - backend:
              service:
                name: keel
                port:
                  number: 31234
            path: /static/
            pathType: Prefix
          - backend:
              service:
                name: console-portal-tenant
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: core-broker
                port:
                  number: 31234
            path: /v1/ws
            pathType: Prefix
          - backend:
              service:
                name: tkeel-docs
                port:
                  number: 3000
            path: /docs
            pathType: Prefix
          