{{- range tuple "private" "public" }}
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ printf "%s-redis-%s-store" $.Chart.Name . }}
  namespace: {{ $.Release.Namespace | quote }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ $.Values.components.state.redis.host }}
  - name: redisPassword
    value: {{ $.Values.components.state.redis.password }}
  {{- if (eq . "public") }}
  - name: keyPrefix
    value: none
  {{- end }}
{{- end }}